version: "3.9"

services:
  security-company-server:
    container_name: security-company-server
    build:
      context: .
    image: zalimannard/security-company-server
    environment:
      - DB_URL=8.8.8.8
      - DB_USER=admin
      - DB_PASSWORD=admin
    ports:
      - "8951:8951"