version: "3.8"

services:
  security-company-server:
    container_name: security-company-server
    build:
      context: .
    image: zalimannard/security-company-server
    ports:
      - "8951:8951"