server:
  port: 8951

spring:
  application:
    name: "security-company-server"
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/security-company-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  # Uncomment for database re-creation
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    path: /docs/api

application:
  endpoint:
    root: /api
    search: /search
    marks: /marks
    places: /places
    organizations: /organizations
    persons: /persons
    posts: /posts
    schedules: /schedules
